apiVersion: apps/v1
kind: Deployment
metadata:
  name: cse
spec:
  replicas: 1
  selector:
    matchLabels:
      app: cse
  template:
    metadata:
      labels:
        app: cse
    spec:
      containers:
      - name: drupal
        image: drupal:7.94-php8.0
        volumeMounts:
        - name: drupal-data
          mountPath: /var/www/html/sites
      volumes:
      - name: drupal-data
        persistentVolumeClaim:
          claimName: drupal-data-pvc
