apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: mysql
spec:
  serviceName: mysql
  replicas: 1
  selector:
    matchLabels:
      app: mysql
  template:
    metadata:
      labels:
        app: mysql
    spec:
      containers:
      - name: mysql
        image: mysql:5.7.40-debian
        args:
        - --ignore-db-dir=lost+found
        env:
        - name: MYSQL_DATABASE
          value:
        - name: MYSQL_USER
          value:
        - name: MYSQL_PASSWORD
          value:
        - name: MYSQL_ROOT_PASSWORD
          value:
        volumeMounts:
        - name: db
          mountPath: /var/lib/mysql
      volumes:
      - name: db
        persistentVolumeClaim:
          claimName: db-pvc
